version: "3.3"
services:
  survey:
    image: 'surveyprod:${TAG-latest}'
    container_name: survey-production
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}/survey
      - PORT
      - BASE_PATH=/survey
      - MONGODB_URL=mongoatlasurl
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.${STACK_NAME?Variable not
          set}-survey-http.rule=PathPrefix(`/survey`)
        - traefik.http.services.${STACK_NAME?Variable not
          set}-survey.loadbalancer.server.port=${PORT}
        - traefik.http.routers.${STACK_NAME?Variable not
          set}-survey-http.middlewares=survey-stripprefix
        - traefik.http.middlewares.survey-stripprefix.stripprefix.prefixes=/survey
    networks:
      - traefik-public
 

networks:
  traefik-public:
    external: true
