version: "3.3"
services:

  survey:
    image: 'surveydev:${TAG-latest}'
    container_name: survey-integrated
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=http://${DOMAIN?Variable not set}/survey
      - PORT
      - BASE_PATH=/survey
      - MONGODB_URL=mongodb://user:userpass@mongodb:27017/data?retryWrites=true&w=majority
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-survey-http.rule=PathPrefix(`/survey`)
      - traefik.http.services.${STACK_NAME?Variable not set}-survey.loadbalancer.server.port=${PORT}
      - traefik.http.routers.${STACK_NAME?Variable not set}-survey-http.middlewares=survey-stripprefix
      - traefik.http.middlewares.survey-stripprefix.stripprefix.prefixes=/survey
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
