version: "3.3"
services:
  survey:
    image: 'surveydev:${TAG-latest}'
    container_name: survey-solo
    volumes:
      - .:/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
      - BASE_PATH=
      - PORT
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - "${SOLODEVPORT}:${PORT}"
    networks:
      - default